### ISSUE TITLE
The performance of training from scratch on ISIC 2016 dataset is very low...

### ISSUE THREAD

**Issue by sugurs** [KaoruMuta/ISIC2016_challenge#2]
Hello, KaoruMuta. Thx for your very nice project on the ISIC 2016 dataset. I have been working on using my own CNN architecture to test on ISIC 2016 dataset. Therefore, I can not use the pre-trained weights from the ImageNet dataset. I did experiments by comparing using or not using pre-trained weight of ResNet50 on ISIC 2016 dataset, while the difference is very large (not using pre-trained weight is much worse). Have you ever tried this before? I think I should first use non-pre-trained ResNet50 with the training parameter settings to get good results on this dataset, and then I can use my own designed architecture. I meet this problem now, could you please give me some suggestions.

**Comment by KaoruMuta** [comment]
@sugurs 
Thank you for watching my repository!
I have never tried to use Deep CNN models without pretraining by ImageNet. So, my suggestion may not be helpful to you.

In my opinion, you try to
- tune hyper-parameter by your own designed architecture (not ResNet-50)
- use deeper model instead of ResNet-50 if you can customize (ex. ResNet-152, DenseNet-161)
- do various Preprocessing, such as data augmentation (horizontal/vertical flip, rotation, RandomResize)

I'm looking forward to hearing good results from you!
